version: '3'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./work:/root/work
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPARK_CONF_DIR: /conf
    depends_on:
      - master
    ports:
      - 8081-8089:8081
    volumes:
      - ./work:/root/work
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077 --host 0.0.0.0
    
