version: '3'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./work:/root/work
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master 

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    ports:
      - 8081:8081
    volumes:
      - ./work:/root/work
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    
  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    ports:
      - 8082:8082
    volumes:
      - ./work:/root/work
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077


